### ISSUE TITLE
plugin not available after npm install

### ISSUE THREAD

**Issue by markl-vesper** [sid88in/serverless-appsync-plugin#137]
Is it advised to install the plugin into a separate deployment from others? Ive got a few stacks in play.

I attempted to add to and existing project and the npm install seemed to go ok and the plugin is listed when I npm list

root@2f255a7a8e00:/marlin-service/base# npm list serverless-appsync-plugin
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
marlin-base-infrastructure@0.0.1 /marlin-service/base
`-- serverless-appsync-plugin@1.0.3

npm info ok

Maybe its some kind of conflict?

I'm getting - Serverless plugin "serverless-appsync-plugin" not found when running sls deploy

Its listed in serverless yml

plugins:
  - serverless-plugin-scripts
  - serverless-appsync-plugin
  - iotvars

Any tips?

**Comment by markl-vesper** [comment]
After digging around in other forums I've done a big of debug

SLS_DEBUG= * sls

Serverless: Load command rollback:function

  Syntax Error -------------------------------------------

  Unexpected token )

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

SyntaxError: Unexpected token )
/marlin-service/base/node_modules/serverless-appsync-plugin/index.js:46
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:87:24)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:85:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:131:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:81:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:64:28)
From previous event:
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:25:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.1
     Serverless Version:     1.22.0

root@2f255a7a8e00:/marlin-service/base#

**Comment by sid88in** [comment]
@markl-vesper I have seen this error before. Looks like you might want to update serverless version on your machine.

**Comment by bboure** [comment]
@markl-vesper did you fix your issue? I have seen that kind of error too and sometimes it was related to using an older version of node.

**Comment by markl-vesper** [comment]
Took a bit of time to try and move forwards on this. Updated to serverless 1.30.0 and still seeing same issue

root@0eb1cb243e6d:/marlin-service/base# SLS_DEBUG=* sls package
.
.
.
.
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function

  Syntax Error -------------------------------------------

  Unexpected token )

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

SyntaxError: Unexpected token )
/marlin-service/base/node_modules/serverless-appsync-plugin/index.js:46
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:90:24)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:88:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:141:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:84:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:70:28)
From previous event:
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:29:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:63:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.1
     Serverless Version:     **1.30.0**

root@0eb1cb243e6d:/marlin-service/base#
