### ISSUE TITLE
Stacktrace when adding a resolver to an existing appsync schema

### ISSUE THREAD

**Issue by adrianhall** [sid88in/serverless-appsync-plugin#184]
Repro steps:
1. Create an appsync schema with a bunch of resolvers
2. Edit serverless.yml to add a resolver (with request/response mapping files)
3. Run `SLS_DEBUG=* sls deploy -v`

The following stack trace is produced:

```
TypeError: Cannot read property 'replace' of undefined
    at ServerlessAppsyncPlugin.getCfnName (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:629:17)
    at flattenedMappingTemplates.reduce (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:553:60)
    at Array.reduce (<anonymous>)
    at ServerlessAppsyncPlugin.getResolverResources (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:543:38)
    at config.forEach.apiConfig (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:187:37)
    at Array.forEach (<anonymous>)
    at ServerlessAppsyncPlugin.addResources (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:170:12)
    at Object.after:aws:package:finalize:mergeCustomProviderResources [as hook] (/Users/adrianha/GitHub/restaurant-reviews/backend/node_modules/serverless-appsync-plugin/index.js:80:77)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at AwsPackage.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:72:51)
From previous event:
    at Object.package:finalize [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:72:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:44:28)
```

Versions:

```
14:55 $ npm ls --depth=0 --json
{
  "name": "restaurant-reviews-backend",
  "version": "1.0.0",
  "dependencies": {
    "serverless": {
      "version": "1.34.1",
      "from": "serverless@^1.34.0",
      "resolved": "https://registry.npmjs.org/serverless/-/serverless-1.34.1.tgz"
    },
    "serverless-appsync-plugin": {
      "version": "1.0.9",
      "from": "serverless-appsync-plugin@^1.0.9",
      "resolved": "https://registry.npmjs.org/serverless-appsync-plugin/-/serverless-appsync-plugin-1.0.9.tgz"
    },
    "serverless-cf-vars": {
      "version": "0.3.0",
      "from": "serverless-cf-vars@0.3.0",
      "resolved": "https://registry.npmjs.org/serverless-cf-vars/-/serverless-cf-vars-0.3.0.tgz"
    }
  }
}
```

**Comment by Mseller** [comment]
@adrianhall How did you solve this problem? I have the same issue.

**Comment by Mseller** [comment]
Found the problem. Had misspelled the "field" part of the dataSource.

**Comment by shortjared** [comment]
Another breadcrumb for the next poor soul to run into this cryptic error: I forgot to add the `dataSource` property to my mapping template.

**Comment by chrispypatt** [comment]
Thank you. Similar to @shortjared, I had ```datasource``` instead of ```dataSource``` 🤦‍♂️

**Comment by bboure** [comment]
Thank you all for your feedbacks on this.
Looks like we could improve the plugin and try to detect this kind of (stupid) mistakes and show a decent error message.

**Comment by seesiva** [comment]
> Thank you. Similar to @shortjared, I had `datasource` instead of `dataSource` 🤦‍♂️

I had the same issue as well. Thanks for noting it down here.

**Comment by alex-percayso** [comment]
If anyone else has this issue, I was on an older version of the plugin, updating it after hours of torture got it working.

**Comment by quentinhayot** [comment]
Hey you! Yes, you having this issue in 2021, asking yourself why this doesn't work anymore when your previous commit did even if you didn't change anything related...
Go git compare your local VS your last commit and you'll find where you deleted a line from your dataSources by accident.  

My `serverless.yml` was not at all missing a `type: Query` from a dataSource that was created months ago and working since then. I swear I'm not that dumb and I didn't waste a full day on this at all. 🙄 🙃

**Comment by tjrunnels** [comment]
ALSO be sure **not** to leave a blank { } in your mapping template.  Serverless will look for dataSource and not find it.
```
  mappingTemplates: [
   ...
         {
                //     type: 'Mutation', 
                //     field: 'createPlantWithPicture',
                //     kind: 'PIPELINE',
                //     functions: ['uploadImageFunction','createPlantFromImage'],
                //     request: 'simplePipeline.request.vtl',
                //     response: 'simplePipeline.response.vtl',
                //  
           },
           {
               type: 'Mutation',
               field: 'deletePhoto',
               dataSource: 'photosTable'
           },
   ...
],
```
^^ this WILL give the error
(i'm using typescript btw)

**Comment by n3s7or** [comment]
**ALSO** make sure to not duplicate a function resolver
