### ISSUE TITLE
Does PipeLine Resolver support Subscription without Functions and Request

### ISSUE THREAD

**Issue by jinjingbo** [sid88in/serverless-appsync-plugin#231]
Hi there, 
I am trying to do this:
```
      - type: Subscription
        field: updatedBatchBySite
        response: 'updatedBySite-after.vtl'
        kind: PIPELINE

      - type: Subscription
        field: updatedRecipeByCompany
        response: 'updatedByCompany-after.vtl'
        kind: PIPELINE
```

It works if i manually add it into AWS AppSync console, with no function, and only add `after-mapping`. 

However If I run via serverless-appsync-plugin, i got error:
```
TypeError: Cannot read property 'map' of undefined
    at flattenedMappingTemplates.reduce (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless-appsync-plugin/index.js:729:42)
    at Array.reduce (<anonymous>)
    at ServerlessAppsyncPlugin.getResolverResources (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless-appsync-plugin/index.js:703:38)
    at config.forEach.apiConfig (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless-appsync-plugin/index.js:261:37)
    at Array.forEach (<anonymous>)
    at ServerlessAppsyncPlugin.addResources (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless-appsync-plugin/index.js:244:12)
    at Object.after:aws:package:finalize:mergeCustomProviderResources [as hook] (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless-appsync-plugin/index.js:85:77)
    at BbPromise.reduce (/home/travis/build/kounta/produce/backend/appsync/node_modules/serverless/lib/classes/PluginManager.js:408:55)
```

Even if I add an empty `before-mapping`:
```
## before mapping
{}
```
Still failing with same error.

Any help is welcome!

**Comment by jinjingbo** [comment]
Eventually I ended up by using `None` DataSource type:
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-none.html

**Comment by gimenna** [comment]
Hi, I'm having the same issue you mentioned here. Could you give me an example about how did you resolve it?

**Comment by Jeff-Duke** [comment]
@jinjingbo do you have an example of how you resolved this? I'm running into this error now while creating a new AppSync endpoint
