### ISSUE TITLE
no such file or directory, when calling getResolverResources

### ISSUE THREAD

**Issue by grayaii** [sid88in/serverless-appsync-plugin#236]
I have 2 machines.
When I call:

    serverless deploy  --stage stage --verbose

It works on one machine, but not the other.  I can't see what the difference is.
They both have the same credentials to AWS, they both ran the same commands.
I just can't figure out why it's working on one machine, but not the other.

The stack trace when it fails is:

```
Serverless: Generated requirements from /foo/back-end/requirements.txt in /foo/back-end/.serverless/requirements.txt...
Serverless: Installing requirements from /foo/back-end/.serverless/requirements/requirements.txt ...
Serverless: Docker Image: lambci/lambda:build-python3.7
Serverless: Running docker run --rm -v /foo/back-end/.serverless/requirements\:/var/task\:z lambci/lambda\:build-python3.7 /bin/sh -c 'python3.7 -m pip install -t /var/task/ -r /var/task/requirements.txt && chown -R 503\\:505 /var/task'...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
AWS Pseudo Parameters
Skipping automatic replacement of regions with account region!
AWS Pseudo Parameter: Resources::GraphQLResolverLambdaFunction::Properties::Role Replaced AWS::AccountId with ${AWS::AccountId}
AWS Pseudo Parameter: Outputs::region::Value Replaced AWS::Region with ${AWS::Region}
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open 'mapping-templates/viewerInfo-request.vtl'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, open 'mapping-templates/viewerInfo-request.vtl'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at flattenedMappingTemplates.reduce (/foo/back-end/node_modules/serverless-appsync-plugin/index.js:706:34)
    at Array.reduce (<anonymous>)
    at ServerlessAppsyncPlugin.getResolverResources (/foo/back-end/node_modules/serverless-appsync-plugin/index.js:703:38)
    at config.forEach.apiConfig (/foo/back-end/node_modules/serverless-appsync-plugin/index.js:261:37)
    at Array.forEach (<anonymous>)
    at ServerlessAppsyncPlugin.addResources (/foo/back-end/node_modules/serverless-appsync-plugin/index.js:244:12)
    at Object.after:aws:package:finalize:mergeCustomProviderResources [as hook] (/foo/back-end/node_modules/serverless-appsync-plugin/index.js:85:77)
    at BbPromise.reduce (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at AwsPackage.BbPromise.bind.then (/foo/back-end/node_modules/serverless/lib/plugins/aws/package/index.js:72:51)
From previous event:
    at Object.package:finalize [as hook] (/foo/back-end/node_modules/serverless/lib/plugins/aws/package/index.js:72:10)
    at BbPromise.reduce (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at Deploy.BbPromise.bind.then (/foo/back-end/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/foo/back-end/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/foo/back-end/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/foo/back-end/node_modules/serverless/lib/Serverless.js:109:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Serverless.run (/foo/back-end/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/foo/back-end/node_modules/serverless/bin/serverless:43:28)
    at /foo/back-end/node_modules/graceful-fs/graceful-fs.js:111:16
    at /foo/back-end/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/foo/back-end/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at __dirname (/foo/back-end/node_modules/serverless/bin/serverless:28:46)
    at Object.<anonymous> (/foo/back-end/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.9.4
     Serverless Version:     1.40.0
```

Any ideas how I can even begin to debug this? Is it a docker issue? Environment issue?

Any help would be great!

Thanks!

**Comment by grayaii** [comment]
I think we are getting closer to figuring it out... it seems to be working on all Macs, but failing on all linux boxes.

We're kinda blindly trying to debug this, but I wanted to post at least that bit of information.

**Comment by grayaii** [comment]
I think we figured it out.  The issue was the  the file name was lower case, and it somehow worked on a mac, but on linux, it was case sensitive.  :(
