### ISSUE TITLE
Enable logConfig raises logGroupName.startsWith is not a function on enterprise-plugin

### ISSUE THREAD

**Issue by vinicius-ronconi** [sid88in/serverless-appsync-plugin#257]
If I don't add the logConfig to my appSync settings, everything runs fine and the stack is properly created.

Then I added the following piece of code to appSync settings:
```
logConfig:
  loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
  level: "ERROR"
```

Here is how AppSyncLoggingServiceRole was declared:
```
Resources:
  AppSyncLoggingServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      RoleName: "testAppSyncServiceRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
```

When I set SLS_DEBUG=* and run a deploy, I get the following error:
```  Type Error ---------------------------------------------

  logGroupName.startsWith is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: logGroupName.startsWith is not a function
    at _callee$ (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/src/lib/logsCollection.js:73:13)
    at tryCatch (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/dist/lib/logsCollection.js:12:103)
    at _next (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/dist/lib/logsCollection.js:14:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:448:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:466:17)
    at AwsPackage.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:72:51)
From previous event:
    at Object.package:finalize [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:72:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:448:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:448:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:466:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:448:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:448:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:479:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:112:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

The error happens in the enterprise-plugin (more specifically here: https://github.com/serverless/enterprise-plugin/blob/master/src/lib/logsCollection.js#L68)

But it happens because the record created by the serverless-appsync-plugin looks like this:
```
  {
    "key": "GraphQlApiLogGroup",
    "resource": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": {
          "Fn::Join": [
            "/",
            [
              "/aws/appsync/apis",
              {
                "Fn::GetAtt": [
                  "GraphQlApi",
                  "ApiId"
                ]
              }
            ]
          ]
        },
        "RetentionInDays": 30
      }
    }
  }
```

Other entries that are successfully processed in this array look like this:
```
  {
    "key": "UpdateUserPointsFnLogGroup",
    "resource": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/testUpdateUserPointsFn",
        "RetentionInDays": 30
      }
    }
  },
```

Since enterprise-plugin was expecting LogGroupName to be a string, the error is raised.

Maybe it is something wrong in my settings, but I was not able to find a way to fix it.
```
This is my current environment:
     OS:                     darwin
     Node Version:           10.16.0
     Serverless Version:     1.46.1
```

**Comment by oakstreetrec** [comment]
I'm getting the same error. Did you end up finding any way to resolve?

**Comment by vinicius-ronconi** [comment]
Not yet. Put it on hold and just disabled the log config. At least, logs are recorded to CloudWatch anyway.

**Comment by oakstreetrec** [comment]
Ok, thanks. Separately I was chatting on the serverless enterprise dashboard with that team and brought up this error. Someone there is going to take a look so maybe we'll see updated logic in logsCollection.js.

**Comment by vinicius-ronconi** [comment]
Great! If there is an publicly available link for this, please share it here. I would love to follow it!

**Comment by oakstreetrec** [comment]
It was just a live chat on the dashboard, but I'll update here if I get any more information.

**Comment by oakstreetrec** [comment]
Gareth from Serverless said he made his team aware of this but because it's an external developer's codebase it's hard to prioritize and don't hold our breath. Better to get someone who works on this codebase to notice the problem and implement a fix.

**Comment by joebernard** [comment]
I'm seeing this error too. It began after I ran `serverless` to set up the serverless dashboard and monitoring for the first time on an existing project. Removing `logConfig` from my settings got me passed the error, thanks for posting the workaround!

**Comment by cameroncf** [comment]
This problem is easily replicated outside of this plugin. I think this can be solved in the enterprise-plugin. See PR above, which fixed the problem for me.

**Comment by joebernard** [comment]
It seems like this one was resolved. I'm able to use the appsync log config again.

serverless: 1.54.0
serverless-appsync-plugin: 1.1.2

**Comment by cameroncf** [comment]
@joebernard Looks like the fix was merged into @serverless/enterprise-plugin on Oct 8 as part of plugin version 3.1.2.

@sid88in This ticket can probably be closed now.
