### ISSUE TITLE
mappingTemplates including file results in ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by inventionlabsSydney** [sid88in/serverless-appsync-plugin#265]
Hi,
Love this plugin, currently encountering an issue related to PR #182 

The following configuration should work:
```
appSync:
. . . redacted. . .
schema:
  - graphql/integrations/schemas/_types.application.graphql
  - graphql/integrations/schemas/_mutations.application.graphql
dataSources:
  - ${file(datasources/dynamodb/products.yml)}
  - ${file(datasources/dynamodb/applications.yml)}
mappingTemplates:
  - ${file(mapping-templates/integrations/routes.yml)}
```

Contents of routes.yml
```
- dataSource: Applications
  type: Query
  field: listApplications
  request: integrations/applications/list/request.vlt
  response: integrations/applications/list/response.vlt
```

Upon starting the offline mode (command `serverless offline start`) I receive:
```
Serverless: ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

Now I believe this is due to this line here: https://github.com/sid88in/serverless-appsync-plugin/blob/4757262f985be5598b6bcdd435d92e978260ac74/index.js#L783

However honestly, I am not entirely sure.
My version information is:
```
    "serverless-appsync-offline": "^1.3.3",
    "serverless-appsync-plugin": "^1.1.2",
    "serverless-dynamodb-local": "^0.2.38",
    "serverless-offline": "^5.8.0",
    "serverless-plugin-aws-alerts": "^1.3.1",
    "serverless-pseudo-parameters": "^2.4.0",
```

Any help would be appreciated, I am unsure how to approach this.

Thanks,
Karl.

**Comment by inventionlabsSydney** [comment]
Sorry to point fingers, I finally got the stack trace from the error and it appears to not be related, just misleading!
```
Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at config.mappingTemplates.reduce (/backend/core-api/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:352:27)
    at Array.reduce (<anonymous>)
    at generateResolvers (/backend/core-api/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:344:34)
    at createSchema (/backend/core-api/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:417:27)
    at createSchema (/backend/core-api/node_modules/@conduitvc/appsync-emulator-serverless/server.js:82:10)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at createServer (/backend/core-api/node_modules/@conduitvc/appsync-emulator-serverless/server.js:99:37)
    at ServerlessAppSyncPlugin.startHandler (/backend/core-api/node_modules/serverless-appsync-offline/index.js:102:22)
    at ServerlessAppSyncPlugin.startHandler (/backend/core-api/node_modules/serverless-appsync-offline/index.js:108:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I will leave this here for anyone else who comes across this but I'm going to move on to conduitvc...

**Comment by vance** [comment]
What was the actual problem here? Getting the same error.

**Comment by inventionlabsSydney** [comment]
I gave up and moved on - yep it's an actual error but it's in relation to the package choices.

**Comment by nicemaker** [comment]
I got the same error, deploying works without problem, but offline mode doesn't work unfortunately.
These are my dependencies:
```
"@types/aws-lambda": "^8.10.63",
    "@types/node": "^14.11.8",
    "serverless": "^2.6.0",
    "serverless-appsync-offline": "^1.4.0",
    "serverless-appsync-plugin": "^1.4.0",
    "serverless-offline": "^6.8.0",
    "serverless-webpack": "^5.3.5",
    "source-map-support": "^0.5.19",
    "ts-loader": "^8.0.5",
    "typescript": "^4.0.3",
    "webpack": "^5.0.0"
```

@inventionlabsSydney How did you get the details of the error. I tried `--verbose` and `SLS_DEBUG=*` but I get nothing but the simple message `Serverless: ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

Not sure if this ticket should be closed, there is no solution mentioned.
