### ISSUE TITLE
Functrions with "-" break 

### ISSUE THREAD

**Issue by jeremiahlukus** [sid88in/serverless-appsync-plugin#311]
when using functions with "-" in it i get 
ex function name is my-function-name
```
 Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource MyDashFunctionDashName
   at provider.request.catch.error (/Users/jparrack/.config/yarn/global/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:13)
    at tryCatcher (/Users/jparrack/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
```

my full yml is this 

```
  appSync:
    name: ${self:service.name}
    authenticationType: AMAZON_COGNITO_USER_POOLS                                                                                                         userPoolConfig:
      awsRegion: 'us-east-1'
      defaultAction: ALLOW
      userPoolId:  us-east-1_blah
    mappingTemplatesLocation: ./graphql
    mappingTemplates:
      - dataSource: myFunction
        type: Query
        field: myFunction
    schema: './schema.graphql'
    dataSources:
      - type: AWS_LAMBDA
        name: 'myFunction'
        description: 'Lambda DataSource'
        config:
          functionName: 'my-function-name'
          serviceRoleArn: 'arn:aws:iam::232767835305:role/appsync-lambda'
```

**Comment by bboure** [comment]
@jeremiahlukus where is `my-function-name` defined?
