### ISSUE TITLE
Cannot find module 'serverless/lib/serverless-error'

### ISSUE THREAD

**Issue by Axum666** [sid88in/serverless-appsync-plugin#585]
Was upgrading from v1 to v2 and ran in to this error "Cannot find module 'serverless/lib/serverless-error'"  (full error below)

The serverless-appsync-plugin had a reference to the Serverless package. Which of course is a dependency as this is a plugin for the other package. However it is not a NPM dependency. which I believe lead to this error

In our environment previously we have serverless installed globaly (npm install -g), and serverless-appsync-plugin as a dev dependency in one submodule of our serverless compose. I resolved this issue by also installing the serverless framework package as a dev dependency in that module alongside serverless-appsync-plugin, and that seemed to resolve  the error. However that is not something we really planned on doing, or needed doing for any other serverless plugin we are using. Unsure if it was related but we also recently switched to Yarn to compose our NPM packages over the multiple serverless services.

As for a solution for this, I'm not sure of the best practice when it comes to plugins for other packages and if serverless should be made a NPM dependency of serverless-appsync-plugin. Or maybe there is a way to access the 'serverless/lib/serverless-error' in code that would invoke the globally installed package instead of requiring a side by side installation. Or if this just needs to be be some documentation changes made to make this clear.

But thought it was worth posting about in case other people had the same issue. 

Error: Cannot find module 'serverless/lib/serverless-error'
Require stack:
- /REDACTED/node_modules/serverless-appsync-plugin/lib/resources/Schema.js
- /REDACTED/node_modules/serverless-appsync-plugin/lib/resources/Api.js
- /REDACTED/node_modules/serverless-appsync-plugin/lib/index.js
- /opt/homebrew/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js
- /opt/homebrew/lib/node_modules/serverless/lib/serverless.js
- /opt/homebrew/lib/node_modules/serverless/scripts/serverless.js
- /opt/homebrew/lib/node_modules/serverless/bin/serverless.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/REDACTED/node_modules/serverless-appsync-plugin/lib/resources/Schema.js:12:42)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/REDACTED/node_modules/serverless-appsync-plugin/lib/resources/Api.js:31:16)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/REDACTED/node_modules/serverless-appsync-plugin/lib/index.js:52:13)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at module.exports (/opt/homebrew/lib/node_modules/serverless/lib/utils/require-with-import-fallback.js:5:12)
    at PluginManager.requireServicePlugin (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
    at PluginManager.loadAllPlugins (/opt/homebrew/lib/node_modules/serverless/lib/classes/plugin-manager.js:136:47)
    at Serverless.init (/opt/homebrew/lib/node_modules/serverless/lib/serverless.js:146:30)
    at async /opt/homebrew/lib/node_modules/serverless/scripts/serverless.js:607:7

**Comment by kuda1992** [comment]
@Axum666 you're a life saver spent two days on this.

**Comment by ShariqAteeq** [comment]
fixed this error by installing serverless package

**Comment by sid88in** [comment]
closing as this has been resolved.
